from __future__ import annotations


def test_health_returns_ok(client) -> None:
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_metrics_endpoint_responds(client) -> None:
    """GET /metrics should return 200 with metrics data or 404 with a clear message."""
    response = client.get("/metrics")
    assert response.status_code in {200, 404}
    body = response.json()
    if response.status_code == 200:
        # metrics.json was generated by train.py
        assert "accuracy" in body
        assert "roc_auc" in body
    else:
        # metrics.json not yet generated — message should guide the user
        assert "detail" in body
        assert "train.py" in body["detail"]
