from __future__ import annotations

import json
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.api.predict import router as predict_router
from app.api.vehicles import router as vehicles_router
from app.config import settings
from app.errors import generic_error_handler, value_error_handler
from app.logging_config import setup_logging
from app.services.prediction_service import get_prediction_service
import logging

_METRICS_PATH = Path(__file__).resolve().parents[2] / "model" / "metrics.json"


@asynccontextmanager
async def lifespan(_: FastAPI):
    log_level = "DEBUG" if settings.debug else "INFO"
    setup_logging(log_level)
    logger = logging.getLogger(__name__)
    try:
        get_prediction_service()
        logger.info("Model loaded successfully")
    except Exception:
        logger.exception("Failed to load prediction model during startup")
    yield


app = FastAPI(
    title="Vehicle Maintenance Prediction API",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(predict_router)
app.include_router(vehicles_router)

app.add_exception_handler(ValueError, value_error_handler)
app.add_exception_handler(Exception, generic_error_handler)


@app.get("/health")
def health() -> dict[str, str]:
    """Liveness probe — returns {status: ok}."""
    return {"status": "ok"}


@app.get("/metrics")
def metrics() -> JSONResponse:
    """Return model evaluation metrics generated by model/train.py.

    Reads ``model/metrics.json`` if present; otherwise returns a 404-style
    message instructing the caller to run the training script first.
    """
    if not _METRICS_PATH.exists():
        return JSONResponse(
            status_code=404,
            content={"detail": "metrics.json not found — run model/train.py to generate it."},
        )
    with open(_METRICS_PATH) as f:
        data = json.load(f)
    return JSONResponse(content=data)

